### ISSUE TITLE
不同prompt对润色结果的影响

### ISSUE THREAD

**Issue by abxm2** [openai-translator/bob-plugin-openai-polisher#14]
「不是bug。因为没有讨论区，就发这里啦。」

Translator的prompt是 “Polish xxxxxxx”
Polisher的prompt是“Revise xxxxxx”

两个同时使用，从结果来看，translator的润色更大胆，句式用词变动更多，可能会改变一些原来的意思。polisher的结果更保守，基本保留了句子原意。
下面提供一个例子。
Original: whereas English writing may first propose the main points of the article.
Translator: In contrast, English writing may initially introduce the main points **before delving into further details.**
Polisher: while in English writing, the main points may be presented first.

两种prompt各有所长，使用“Polish xxxx”的prompt润色的更明显

**Comment by yetone** [comment]
哈哈，感谢反馈和提醒！已开通讨论区！

**Comment by reycn** [comment]
Polisher 的 prompt 是我写的，是我刻意的。
主要两点：
1、通常教你写作的老师会强调 revise/revision 所以可能模型来源语料上 revise 质量更高；
2、就润色任务，不是太希望它改动太大，因为 GPT3 常常遇到逻辑被改的情况，GPT4 会有改善。

**Comment by reycn** [comment]
> 

补充一下，一般来讲这些深度学习都是文本向量化 -> 学习和训练，所以如何找到最合适的文本（提示）是很重要的，一起摸索~

**Comment by liby** [comment]
[v0.2.0 (release)](https://github.com/openai-translator/bob-plugin-openai-polisher/releases/tag/v0.2.0) 已支持自定义 System Prompt 和 User Prompt
