### ISSUE TITLE
API URL 如果没有填，或者被删掉，缺省自动使用 https://api.openai.com 

### ISSUE THREAD

**Issue by eyestudio** [openai-translator/bob-plugin-openai-polisher#21]
刚升级了版本，把apikey输到 API URL 了，发现错了以后，删掉了 API URL 的内容。结果一致报错，不知道原因，费了半天劲才发现这个问题，建议API URL 如果没有填，或者被删掉，缺省自动使用 https://api.openai.com

**Comment by liby** [comment]
https://github.com/openai-translator/bob-plugin-openai-polisher/releases/tag/v0.2.0
