### ISSUE TITLE
显示“接口响应错误 - Too Many Requests”

### ISSUE THREAD

**Issue by wade657** [openai-translator/bob-plugin-openai-polisher#26]
请问这个如何处理呢？没有使用很多，试了各种方法都不行。多谢

![Xnip2023-06-02_10-41-14](https://github.com/openai-translator/bob-plugin-openai-polisher/assets/135347997/e312186c-50be-4788-828f-80d9068bec97)

**Comment by liby** [comment]
https://github.com/openai-translator/bob-plugin-openai-translator/issues/47#issuecomment-1573135854

**Comment by wade657** [comment]
谢谢回复，可是我的usage 没有超，请看下面的截图。麻烦请教下这个该如何解决？谢谢

[image: image.png]
