### ISSUE TITLE
[bug] 默认Prompt对日语润色基本无效

### ISSUE THREAD

**Issue by 5mdld** [openai-translator/bob-plugin-openai-polisher#28]
您好，

如图所示，在GPT-3.5下，默认Prompt对日语的润色基本无效，绝大多数情况都是回答了我输入的内容而不是润色
目前没有GPT-4 API 所以不能测试4.0的效果
![CleanShot 2023-06-09 at 10 16 45@2x](https://github.com/openai-translator/bob-plugin-openai-polisher/assets/88809953/11a25cbf-1e65-4515-9048-48e5196673b9)

**Comment by liby** [comment]
修了一下，另外看起来 GPT-4 会更聪明一点，更新到 v1.2.0 后，你可以尝试修改用户指令试试
<img width="965" alt="image" src="https://github.com/openai-translator/bob-plugin-openai-polisher/assets/38807139/e89efa57-80e2-42ed-a099-25cf8848f213">
