### ISSUE TITLE
在润色模式（详尽）下建议润色原因的语言为可选状态

### ISSUE THREAD

**Issue by ithou** [openai-translator/bob-plugin-openai-polisher#5]
这样做的目的是，有时候原因还得需要重新翻译一下，显得更加繁琐。这是我个人的看法。
<img width="406" alt="image" src="https://user-images.githubusercontent.com/39048771/222943033-a8237b28-0b78-4977-9313-56e5499efbe7.png">

**Comment by reycn** [comment]
原因是gpt自动生成的，再翻译一遍有点浪费token。

**Comment by ithou** [comment]
> 

了解，谢谢。

**Comment by liby** [comment]
https://github.com/openai-translator/bob-plugin-openai-polisher/releases/tag/v0.2.0 支持自定义 System Prompt 和 User Prompt，理论上用户可以通过此功能来达到同样的目的
